### ISSUE TITLE
Mauvais Sujet 2027 + Apport Sujet/Correction S3 Midterm Maths 2027

### ISSUE THREAD

**Issue by amnezicOnly** [Epidocs/Past-Exams#114]
* **I'm submitting ...**
- [ ] a bug report
- [x] a feature request
- [ ] a support request

* **Describe your issue or idea:**
Le sujet sujet de S3 Midterm Maths 2027 est en fait le sujet de celui des 2026. (pareil pour la correction et pour les anglophones.

J'ai mis en pj (normalement) le sujet de maths de midterm S3 avec la correction (version française pour les 2).

[Sujet_Midterms.pdf](https://github.com/Epidocs/Past-Exams/files/13347406/Sujet_Midterms.pdf)
[S3-2023-Mi-Semestre-Corrigé.pdf](https://github.com/Epidocs/Past-Exams/files/13347409/S3-2023-Mi-Semestre-Corrige.pdf)

**Comment by matiboux** [comment]
Thanks for this report.

Some of the S3 Midterms Maths 2027 files are indeed wrong:
- [`/S3/Midterms/Maths/2027/midterm-2027-s3-maths-subject-fr.pdf`](https://github.com/Epidocs/Past-Exams/blob/25412749d2da0e1ef572c6eed958e526f7179fc5/S3/Midterms/Maths/2027/midterm-2027-s3-maths-subject-fr.pdf) ❌
- [`/S3/Midterms/Maths/2027/midterm-2027-s3-maths-subject-en.pdf`](https://github.com/Epidocs/Past-Exams/blob/25412749d2da0e1ef572c6eed958e526f7179fc5/S3/Midterms/Maths/2027/midterm-2027-s3-maths-subject-en.pdf) ❌

These two subject files are from November 2022 and the same as 2026 subject files, yet slightly heavier.

However, these correction files are correct and from October 2023:

- [`/S3/Midterms/Maths/2027/midterm-2027-s3-maths-correction-fr.pdf`](https://github.com/Epidocs/Past-Exams/blob/25412749d2da0e1ef572c6eed958e526f7179fc5/S3/Midterms/Maths/2027/midterm-2027-s3-maths-correction-fr.pdf) ✅
- [`/S3/Midterms/Maths/2027/midterm-2027-s3-maths-correction-en.pdf`](https://github.com/Epidocs/Past-Exams/blob/25412749d2da0e1ef572c6eed958e526f7179fc5/S3/Midterms/Maths/2027/midterm-2027-s3-maths-correction-en.pdf) ✅

Can you open a PR to fix these two files?

@1somniak, would you kindly look into this as well? As you may have the correct files, including the english vesrsion.

**Comment by 1somniak** [comment]
I have done my pull request
